Перенесён синтезатор в рамках следственного эксперимента.
animusdev/Old-World-Blue pull request #263
Opened 2017-03-08 17:53 UTC by Viol

Протестировал на локалке. Как ни странно, всё работает, в отличие от ВГ.

2017-03-08 19:35 UTC, LethalGhost commented
Использовать имена людей в структуре файлов - дурная идея.

2017-03-09 08:00 UTC, Viol commented
Изменил структуру файлов. Классическая папка WorkInProgress, в ней традиционно код в папке с ником своего мейнтейнера.

2017-03-09 13:24 UTC, Euronem commented
![default](https://cloud.githubusercontent.com/assets/17518355/23752033/ce44df90-04e4-11e7-9737-32c00308c856.png)


лол

2017-03-09 13:24 UTC, ghost requested changes
тебе локалку на что дали.

2017-03-09 13:25 UTC, Euronem commented
![default](https://cloud.githubusercontent.com/assets/17518355/23752092/03151d7a-04e5-11e7-81a0-53f4fab3bfcc.png)

2017-03-09 13:25 UTC, Euronem commented
![default](https://cloud.githubusercontent.com/assets/17518355/23752104/0d453172-04e5-11e7-9379-5f7e44bb82b8.png)

2017-03-10 22:46 UTC, closed without merging