Сделал тонкоспрайт для хардсьюта РД. Как бы я долго не просил сделать его, всё равно лучше самому сделать.
animusdev/Old-World-Blue pull request #308
Opened 2017-04-24 19:38 UTC by Voldirs

2017-04-24 21:05 UTC, Aidff commented
Так незаметно впиливать правку точности, это надо уметь, да

2017-04-24 21:50 UTC, alfacom commented
Бекдоры через правку точности заливаешь, да??

2017-04-24 22:24 UTC, Voldirs commented
Конечно, бэкдорчики, как же без них. На самом деле я объебался с гитхабом. Мне нужно только файл со спрайтами занести

2017-04-24 23:08 UTC, alfacom commented
Ветки(branches) как раз для этого неплохи. Создаешь ветку от последнего коммита, кидаешь свои изменения в только что созданную ветку и льешь сюда из своей ветки. Получаем опрятный пулл реквест с одним изменением и на одного Айдффа и одного Алфакома меньше ;)

2017-04-25 04:59 UTC, LethalGhost submitted a review, later dismissed

2017-04-25 05:01 UTC, LethalGhost commented
@Voldirs, это не тот файл.
Вернее, тот, но ты не переписал старый, а добавил новый в корень билда.

2017-04-25 05:02 UTC, LethalGhost requested changes
@Voldirs, это не тот файл.
Вернее, тот, но ты не переписал старый, а добавил новый в корень билда.

2017-04-25 06:37 UTC, Quardbreak commented
Легче спросить "скрины с теста"

2017-04-25 08:37 UTC, closed without merging